dbHost:
  127.0.0.1
application:
  version: @pom.version@
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wanou-system?useUnicode=true&amp;amp;characterEncoding=utf8mb4
    username: root
    password: wxy31425
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 40
      max-idle: 30
      max-wait: 3000
      min-idle: 10
      initial-size: 5
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 1800000
      test-on-borrow: false
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # 测试服务器使用的 不是InnoDB
        dialect: org.hibernate.dialect.MySQLDialect
    application:
      name:  @pom.artifactId@

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
